[Snowflake]
User = 'roshan.abady@myob.com'
Password = ''
Account = 'bu20658.ap-southeast-2'
Authenticator = 'externalbrowser'
Role = 'OPERATIONS_ANALYTICS_MEMBER_AD'
Warehouse = 'OPERATIONS_ANALYTICS_WAREHOUSE_PROD'
Database = 'OPERATIONS_ANALYTICS'
Schema = 'RAW'

[azure_ad]
CLIENT_ID = "fb780ba9-10da-46ae-8a4c-67aa4e5dded1"
TENANT_ID = "ec47f5ff-c7b8-4848-8659-11c2c424d120"
REDIRECT_URI = "https://bu20658.ap-southeast-2.snowflakecomputing.com/fed/login"
