create or replace TABLE TE_ARR_ADJ (
	CLIENT_ID VARCHAR(256),
	ACCOUNT_NAME VARCHAR(256),
	SEATS_ADDED VARCHAR(256),
	AMV_EX_GST FLOAT,
	SELLER_NAME VARCHAR(256),
	NUM_ADDED_MODULE_A VARCHAR(256),
	NUM_ADDED_MODULE_B VARCHAR(256),
	AMV_EX_GST_MODULE_A FLOAT,
	AMV_EX_GST_MODULE_B FLOAT,
	MONTHID VARCHAR(256),
	COMMENT VARCHAR(256)
)COMMENT='Manual ARR adjustments for Tall Emu leaderboard data'
;