[Snowflake]
User = ''
Password = ''
Account = 'bu20658.ap-southeast-2'
Authenticator = 'externalbrowser'
Role = 'OPERATIONS_ANALYTICS_MEMBER_AD'
Warehouse = 'OPERATIONS_ANALYTICS_WAREHOUSE_PROD'
Database = 'OPERATIONS_ANALYTICS'
Schema = 'RAW'
